'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace CovisolR
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="GetDatosPortBinding", [Namespace]:="http://webservices.covisolweb/")>  _
    Partial Public Class GetDatosService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getListRecargasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getConsumosTelepeajeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getFacturasTelepeajeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getListSaldoTarjetasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getListTarjetasRecPendOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ISL.Win.My.MySettings.Default.ISL_Win_CovisolR_GetDatosService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getListRecargasCompleted As getListRecargasCompletedEventHandler
        
        '''<remarks/>
        Public Event getConsumosTelepeajeCompleted As getConsumosTelepeajeCompletedEventHandler
        
        '''<remarks/>
        Public Event getFacturasTelepeajeCompleted As getFacturasTelepeajeCompletedEventHandler
        
        '''<remarks/>
        Public Event getListSaldoTarjetasCompleted As getListSaldoTarjetasCompletedEventHandler
        
        '''<remarks/>
        Public Event getListTarjetasRecPendCompleted As getListTarjetasRecPendCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://webservices.covisolweb/", ResponseNamespace:="http://webservices.covisolweb/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getListRecargas(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg0 As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg1 As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg2 As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg3 As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg4 As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> saldo()
            Dim results() As Object = Me.Invoke("getListRecargas", New Object() {arg0, arg1, arg2, arg3, arg4})
            Return CType(results(0),saldo())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getListRecargasAsync(ByVal arg0 As String, ByVal arg1 As String, ByVal arg2 As String, ByVal arg3 As String, ByVal arg4 As String)
            Me.getListRecargasAsync(arg0, arg1, arg2, arg3, arg4, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getListRecargasAsync(ByVal arg0 As String, ByVal arg1 As String, ByVal arg2 As String, ByVal arg3 As String, ByVal arg4 As String, ByVal userState As Object)
            If (Me.getListRecargasOperationCompleted Is Nothing) Then
                Me.getListRecargasOperationCompleted = AddressOf Me.OngetListRecargasOperationCompleted
            End If
            Me.InvokeAsync("getListRecargas", New Object() {arg0, arg1, arg2, arg3, arg4}, Me.getListRecargasOperationCompleted, userState)
        End Sub
        
        Private Sub OngetListRecargasOperationCompleted(ByVal arg As Object)
            If (Not (Me.getListRecargasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getListRecargasCompleted(Me, New getListRecargasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://webservices.covisolweb/", ResponseNamespace:="http://webservices.covisolweb/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getConsumosTelepeaje(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg0 As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg1 As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg2 As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg3 As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> saldoTP()
            Dim results() As Object = Me.Invoke("getConsumosTelepeaje", New Object() {arg0, arg1, arg2, arg3})
            Return CType(results(0),saldoTP())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getConsumosTelepeajeAsync(ByVal arg0 As String, ByVal arg1 As String, ByVal arg2 As String, ByVal arg3 As String)
            Me.getConsumosTelepeajeAsync(arg0, arg1, arg2, arg3, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getConsumosTelepeajeAsync(ByVal arg0 As String, ByVal arg1 As String, ByVal arg2 As String, ByVal arg3 As String, ByVal userState As Object)
            If (Me.getConsumosTelepeajeOperationCompleted Is Nothing) Then
                Me.getConsumosTelepeajeOperationCompleted = AddressOf Me.OngetConsumosTelepeajeOperationCompleted
            End If
            Me.InvokeAsync("getConsumosTelepeaje", New Object() {arg0, arg1, arg2, arg3}, Me.getConsumosTelepeajeOperationCompleted, userState)
        End Sub
        
        Private Sub OngetConsumosTelepeajeOperationCompleted(ByVal arg As Object)
            If (Not (Me.getConsumosTelepeajeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getConsumosTelepeajeCompleted(Me, New getConsumosTelepeajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://webservices.covisolweb/", ResponseNamespace:="http://webservices.covisolweb/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getFacturasTelepeaje(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg0 As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg1 As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg2 As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg3 As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> xDocumentoETP()
            Dim results() As Object = Me.Invoke("getFacturasTelepeaje", New Object() {arg0, arg1, arg2, arg3})
            Return CType(results(0),xDocumentoETP())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getFacturasTelepeajeAsync(ByVal arg0 As String, ByVal arg1 As String, ByVal arg2 As String, ByVal arg3 As String)
            Me.getFacturasTelepeajeAsync(arg0, arg1, arg2, arg3, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getFacturasTelepeajeAsync(ByVal arg0 As String, ByVal arg1 As String, ByVal arg2 As String, ByVal arg3 As String, ByVal userState As Object)
            If (Me.getFacturasTelepeajeOperationCompleted Is Nothing) Then
                Me.getFacturasTelepeajeOperationCompleted = AddressOf Me.OngetFacturasTelepeajeOperationCompleted
            End If
            Me.InvokeAsync("getFacturasTelepeaje", New Object() {arg0, arg1, arg2, arg3}, Me.getFacturasTelepeajeOperationCompleted, userState)
        End Sub
        
        Private Sub OngetFacturasTelepeajeOperationCompleted(ByVal arg As Object)
            If (Not (Me.getFacturasTelepeajeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getFacturasTelepeajeCompleted(Me, New getFacturasTelepeajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://webservices.covisolweb/", ResponseNamespace:="http://webservices.covisolweb/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getListSaldoTarjetas(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg0 As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg1 As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg2 As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> tarjeta()
            Dim results() As Object = Me.Invoke("getListSaldoTarjetas", New Object() {arg0, arg1, arg2})
            Return CType(results(0),tarjeta())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getListSaldoTarjetasAsync(ByVal arg0 As String, ByVal arg1 As String, ByVal arg2 As String)
            Me.getListSaldoTarjetasAsync(arg0, arg1, arg2, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getListSaldoTarjetasAsync(ByVal arg0 As String, ByVal arg1 As String, ByVal arg2 As String, ByVal userState As Object)
            If (Me.getListSaldoTarjetasOperationCompleted Is Nothing) Then
                Me.getListSaldoTarjetasOperationCompleted = AddressOf Me.OngetListSaldoTarjetasOperationCompleted
            End If
            Me.InvokeAsync("getListSaldoTarjetas", New Object() {arg0, arg1, arg2}, Me.getListSaldoTarjetasOperationCompleted, userState)
        End Sub
        
        Private Sub OngetListSaldoTarjetasOperationCompleted(ByVal arg As Object)
            If (Not (Me.getListSaldoTarjetasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getListSaldoTarjetasCompleted(Me, New getListSaldoTarjetasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://webservices.covisolweb/", ResponseNamespace:="http://webservices.covisolweb/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getListTarjetasRecPend(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg0 As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg1 As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> tarjetaRecPend()
            Dim results() As Object = Me.Invoke("getListTarjetasRecPend", New Object() {arg0, arg1})
            Return CType(results(0),tarjetaRecPend())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getListTarjetasRecPendAsync(ByVal arg0 As String, ByVal arg1 As String)
            Me.getListTarjetasRecPendAsync(arg0, arg1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getListTarjetasRecPendAsync(ByVal arg0 As String, ByVal arg1 As String, ByVal userState As Object)
            If (Me.getListTarjetasRecPendOperationCompleted Is Nothing) Then
                Me.getListTarjetasRecPendOperationCompleted = AddressOf Me.OngetListTarjetasRecPendOperationCompleted
            End If
            Me.InvokeAsync("getListTarjetasRecPend", New Object() {arg0, arg1}, Me.getListTarjetasRecPendOperationCompleted, userState)
        End Sub
        
        Private Sub OngetListTarjetasRecPendOperationCompleted(ByVal arg As Object)
            If (Not (Me.getListTarjetasRecPendCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getListTarjetasRecPendCompleted(Me, New getListTarjetasRecPendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://webservices.covisolweb/")>  _
    Partial Public Class saldo
        
        Private cantidadField As Decimal
        
        Private cantidadFieldSpecified As Boolean
        
        Private fechaHoraField As String
        
        Private lugarField As String
        
        Private numeroField As String
        
        Private placaField As String
        
        Private tipoField As String
        
        Private nCardField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property cantidadSpecified() As Boolean
            Get
                Return Me.cantidadFieldSpecified
            End Get
            Set
                Me.cantidadFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaHora() As String
            Get
                Return Me.fechaHoraField
            End Get
            Set
                Me.fechaHoraField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property lugar() As String
            Get
                Return Me.lugarField
            End Get
            Set
                Me.lugarField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property placa() As String
            Get
                Return Me.placaField
            End Get
            Set
                Me.placaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nCard() As String
            Get
                Return Me.nCardField
            End Get
            Set
                Me.nCardField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://webservices.covisolweb/")>  _
    Partial Public Class tarjetaRecPend
        
        Private cantidadField As Decimal
        
        Private cantidadFieldSpecified As Boolean
        
        Private fechaField As String
        
        Private idField As String
        
        Private ncardField As String
        
        Private numeroField As Decimal
        
        Private numeroFieldSpecified As Boolean
        
        Private razonsocialField As String
        
        Private rucField As String
        
        Private serieField As String
        
        Private tipoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property cantidadSpecified() As Boolean
            Get
                Return Me.cantidadFieldSpecified
            End Get
            Set
                Me.cantidadFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ncard() As String
            Get
                Return Me.ncardField
            End Get
            Set
                Me.ncardField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numero() As Decimal
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property numeroSpecified() As Boolean
            Get
                Return Me.numeroFieldSpecified
            End Get
            Set
                Me.numeroFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property razonsocial() As String
            Get
                Return Me.razonsocialField
            End Get
            Set
                Me.razonsocialField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ruc() As String
            Get
                Return Me.rucField
            End Get
            Set
                Me.rucField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://webservices.covisolweb/")>  _
    Partial Public Class tarjeta
        
        Private entradaField As Decimal
        
        Private entradaFieldSpecified As Boolean
        
        Private ncardField As String
        
        Private salidaField As Decimal
        
        Private salidaFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property entrada() As Decimal
            Get
                Return Me.entradaField
            End Get
            Set
                Me.entradaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property entradaSpecified() As Boolean
            Get
                Return Me.entradaFieldSpecified
            End Get
            Set
                Me.entradaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ncard() As String
            Get
                Return Me.ncardField
            End Get
            Set
                Me.ncardField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property salida() As Decimal
            Get
                Return Me.salidaField
            End Get
            Set
                Me.salidaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property salidaSpecified() As Boolean
            Get
                Return Me.salidaFieldSpecified
            End Get
            Set
                Me.salidaFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://webservices.covisolweb/")>  _
    Partial Public Class empresa
        
        Private contactoField As String
        
        Private departamentoField As String
        
        Private direccionField As String
        
        Private distritoField As String
        
        Private emailField As String
        
        Private nombreField As String
        
        Private provinciaField As String
        
        Private rucField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property contacto() As String
            Get
                Return Me.contactoField
            End Get
            Set
                Me.contactoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property departamento() As String
            Get
                Return Me.departamentoField
            End Get
            Set
                Me.departamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property distrito() As String
            Get
                Return Me.distritoField
            End Get
            Set
                Me.distritoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property provincia() As String
            Get
                Return Me.provinciaField
            End Get
            Set
                Me.provinciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ruc() As String
            Get
                Return Me.rucField
            End Get
            Set
                Me.rucField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://webservices.covisolweb/")>  _
    Partial Public Class xDocumentoETP
        
        Private codProductoField As String
        
        Private departamentoField As String
        
        Private descProductoField As String
        
        Private descProducto1Field As String
        
        Private direccionClienteField As String
        
        Private distritoField As String
        
        Private empresaField As empresa
        
        Private estadoField As String
        
        Private fechaEmisionField As String
        
        Private fechaSubidaField As String
        
        Private igvField As Decimal
        
        Private igvFieldSpecified As Boolean
        
        Private keyField As String
        
        Private nombreClienteField As String
        
        Private numeroField As Decimal
        
        Private numeroFieldSpecified As Boolean
        
        Private numeroDocClienteField As String
        
        Private numeroRefField As Decimal
        
        Private numeroRefFieldSpecified As Boolean
        
        Private porcentajeigvField As Decimal
        
        Private porcentajeigvFieldSpecified As Boolean
        
        Private provinciaField As String
        
        Private serieField As String
        
        Private serieRefField As String
        
        Private subTotalField As Decimal
        
        Private subTotalFieldSpecified As Boolean
        
        Private tipoField As String
        
        Private tipoDocClienteField As String
        
        Private tipoMonedaField As String
        
        Private tipoRefField As String
        
        Private tipoVentaField As String
        
        Private totalField As Decimal
        
        Private totalFieldSpecified As Boolean
        
        Private urlField As String
        
        Private usuarioField As String
        
        Private valorResumenField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codProducto() As String
            Get
                Return Me.codProductoField
            End Get
            Set
                Me.codProductoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property departamento() As String
            Get
                Return Me.departamentoField
            End Get
            Set
                Me.departamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descProducto() As String
            Get
                Return Me.descProductoField
            End Get
            Set
                Me.descProductoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descProducto1() As String
            Get
                Return Me.descProducto1Field
            End Get
            Set
                Me.descProducto1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property direccionCliente() As String
            Get
                Return Me.direccionClienteField
            End Get
            Set
                Me.direccionClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property distrito() As String
            Get
                Return Me.distritoField
            End Get
            Set
                Me.distritoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property empresa() As empresa
            Get
                Return Me.empresaField
            End Get
            Set
                Me.empresaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaEmision() As String
            Get
                Return Me.fechaEmisionField
            End Get
            Set
                Me.fechaEmisionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaSubida() As String
            Get
                Return Me.fechaSubidaField
            End Get
            Set
                Me.fechaSubidaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property igv() As Decimal
            Get
                Return Me.igvField
            End Get
            Set
                Me.igvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property igvSpecified() As Boolean
            Get
                Return Me.igvFieldSpecified
            End Get
            Set
                Me.igvFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombreCliente() As String
            Get
                Return Me.nombreClienteField
            End Get
            Set
                Me.nombreClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numero() As Decimal
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property numeroSpecified() As Boolean
            Get
                Return Me.numeroFieldSpecified
            End Get
            Set
                Me.numeroFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroDocCliente() As String
            Get
                Return Me.numeroDocClienteField
            End Get
            Set
                Me.numeroDocClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroRef() As Decimal
            Get
                Return Me.numeroRefField
            End Get
            Set
                Me.numeroRefField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property numeroRefSpecified() As Boolean
            Get
                Return Me.numeroRefFieldSpecified
            End Get
            Set
                Me.numeroRefFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property porcentajeigv() As Decimal
            Get
                Return Me.porcentajeigvField
            End Get
            Set
                Me.porcentajeigvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property porcentajeigvSpecified() As Boolean
            Get
                Return Me.porcentajeigvFieldSpecified
            End Get
            Set
                Me.porcentajeigvFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property provincia() As String
            Get
                Return Me.provinciaField
            End Get
            Set
                Me.provinciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property serieRef() As String
            Get
                Return Me.serieRefField
            End Get
            Set
                Me.serieRefField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property subTotal() As Decimal
            Get
                Return Me.subTotalField
            End Get
            Set
                Me.subTotalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property subTotalSpecified() As Boolean
            Get
                Return Me.subTotalFieldSpecified
            End Get
            Set
                Me.subTotalFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoDocCliente() As String
            Get
                Return Me.tipoDocClienteField
            End Get
            Set
                Me.tipoDocClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoMoneda() As String
            Get
                Return Me.tipoMonedaField
            End Get
            Set
                Me.tipoMonedaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoRef() As String
            Get
                Return Me.tipoRefField
            End Get
            Set
                Me.tipoRefField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoVenta() As String
            Get
                Return Me.tipoVentaField
            End Get
            Set
                Me.tipoVentaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property total() As Decimal
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property totalSpecified() As Boolean
            Get
                Return Me.totalFieldSpecified
            End Get
            Set
                Me.totalFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property url() As String
            Get
                Return Me.urlField
            End Get
            Set
                Me.urlField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property valorResumen() As String
            Get
                Return Me.valorResumenField
            End Get
            Set
                Me.valorResumenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://webservices.covisolweb/")>  _
    Partial Public Class saldoTP
        
        Private cantidadField As Decimal
        
        Private cantidadFieldSpecified As Boolean
        
        Private fechaHoraField As String
        
        Private lugarField As String
        
        Private numeroField As String
        
        Private numerodocField As Decimal
        
        Private numerodocFieldSpecified As Boolean
        
        Private placaField As String
        
        Private seriedocField As String
        
        Private tipoField As String
        
        Private tipodocField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property cantidadSpecified() As Boolean
            Get
                Return Me.cantidadFieldSpecified
            End Get
            Set
                Me.cantidadFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaHora() As String
            Get
                Return Me.fechaHoraField
            End Get
            Set
                Me.fechaHoraField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property lugar() As String
            Get
                Return Me.lugarField
            End Get
            Set
                Me.lugarField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numerodoc() As Decimal
            Get
                Return Me.numerodocField
            End Get
            Set
                Me.numerodocField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property numerodocSpecified() As Boolean
            Get
                Return Me.numerodocFieldSpecified
            End Get
            Set
                Me.numerodocFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property placa() As String
            Get
                Return Me.placaField
            End Get
            Set
                Me.placaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property seriedoc() As String
            Get
                Return Me.seriedocField
            End Get
            Set
                Me.seriedocField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipodoc() As String
            Get
                Return Me.tipodocField
            End Get
            Set
                Me.tipodocField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub getListRecargasCompletedEventHandler(ByVal sender As Object, ByVal e As getListRecargasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getListRecargasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As saldo()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),saldo())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub getConsumosTelepeajeCompletedEventHandler(ByVal sender As Object, ByVal e As getConsumosTelepeajeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getConsumosTelepeajeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As saldoTP()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),saldoTP())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub getFacturasTelepeajeCompletedEventHandler(ByVal sender As Object, ByVal e As getFacturasTelepeajeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getFacturasTelepeajeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As xDocumentoETP()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),xDocumentoETP())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub getListSaldoTarjetasCompletedEventHandler(ByVal sender As Object, ByVal e As getListSaldoTarjetasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getListSaldoTarjetasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As tarjeta()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),tarjeta())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub getListTarjetasRecPendCompletedEventHandler(ByVal sender As Object, ByVal e As getListTarjetasRecPendCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getListTarjetasRecPendCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As tarjetaRecPend()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),tarjetaRecPend())
            End Get
        End Property
    End Class
End Namespace
