'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace com.grupoinduamerica
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ReferenciaServicioFacturaBinding", [Namespace]:="urn:ReferenciaServicioFactura")>  _
    Partial Public Class ReferenciaServicioFactura
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private enviardataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ISL.LogicaWCF.My.MySettings.Default.ISL_LogicaWCF_com_grupoinduamerica_ReferenciaServicioFactura
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event enviardataCompleted As enviardataCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ReferenciaServicioFactura#enviardata", RequestNamespace:="urn:ReferenciaServicioFactura", ResponseNamespace:="urn:ReferenciaServicioFactura")>  _
        Public Function enviardata(ByVal accion As String, ByVal envio As String, ByVal id As String, ByVal valor As String, ByVal key As String) As <System.Xml.Serialization.SoapElementAttribute("retorno")> String
            Dim results() As Object = Me.Invoke("enviardata", New Object() {accion, envio, id, valor, key})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub enviardataAsync(ByVal accion As String, ByVal envio As String, ByVal id As String, ByVal valor As String, ByVal key As String)
            Me.enviardataAsync(accion, envio, id, valor, key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub enviardataAsync(ByVal accion As String, ByVal envio As String, ByVal id As String, ByVal valor As String, ByVal key As String, ByVal userState As Object)
            If (Me.enviardataOperationCompleted Is Nothing) Then
                Me.enviardataOperationCompleted = AddressOf Me.OnenviardataOperationCompleted
            End If
            Me.InvokeAsync("enviardata", New Object() {accion, envio, id, valor, key}, Me.enviardataOperationCompleted, userState)
        End Sub
        
        Private Sub OnenviardataOperationCompleted(ByVal arg As Object)
            If (Not (Me.enviardataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent enviardataCompleted(Me, New enviardataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub enviardataCompletedEventHandler(ByVal sender As Object, ByVal e As enviardataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class enviardataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
