'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18449
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace listarPecsa
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TransaccionInfo", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TransaccionInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PlacaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaDocumentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DocumentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KmField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductoField As String
        
        Private CantidadField As Double
        
        Private TotalField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TarjetaField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Estacion() As String
            Get
                Return Me.EstacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstacionField, value) <> true) Then
                    Me.EstacionField = value
                    Me.RaisePropertyChanged("Estacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Placa() As String
            Get
                Return Me.PlacaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PlacaField, value) <> true) Then
                    Me.PlacaField = value
                    Me.RaisePropertyChanged("Placa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property FechaDocumento() As String
            Get
                Return Me.FechaDocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaDocumentoField, value) <> true) Then
                    Me.FechaDocumentoField = value
                    Me.RaisePropertyChanged("FechaDocumento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Documento() As String
            Get
                Return Me.DocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DocumentoField, value) <> true) Then
                    Me.DocumentoField = value
                    Me.RaisePropertyChanged("Documento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Km() As String
            Get
                Return Me.KmField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KmField, value) <> true) Then
                    Me.KmField = value
                    Me.RaisePropertyChanged("Km")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property Producto() As String
            Get
                Return Me.ProductoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductoField, value) <> true) Then
                    Me.ProductoField = value
                    Me.RaisePropertyChanged("Producto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property Cantidad() As Double
            Get
                Return Me.CantidadField
            End Get
            Set
                If (Me.CantidadField.Equals(value) <> true) Then
                    Me.CantidadField = value
                    Me.RaisePropertyChanged("Cantidad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=7)>  _
        Public Property Total() As Double
            Get
                Return Me.TotalField
            End Get
            Set
                If (Me.TotalField.Equals(value) <> true) Then
                    Me.TotalField = value
                    Me.RaisePropertyChanged("Total")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property Tarjeta() As String
            Get
                Return Me.TarjetaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TarjetaField, value) <> true) Then
                    Me.TarjetaField = value
                    Me.RaisePropertyChanged("Tarjeta")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SiteInfo", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SiteInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SiteidField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CityidField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CountryidField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Addr1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdPaisField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdDepartamentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdProvinciaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdDistritoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdRegionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PaisField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartamentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProvinciaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DistritoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Addr2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Fono1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Fono2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaxField As String
        
        Private StatusField As System.Nullable(Of Boolean)
        
        Private StartdateinvenField As System.Nullable(Of Date)
        
        Private EnddateinvenField As System.Nullable(Of Date)
        
        Private AdjustField As System.Nullable(Of Boolean)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AttnField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UseridField As String
        
        Private StknewField As Boolean
        
        Private StkmodifyField As Boolean
        
        Private StkdeleteField As Boolean
        
        Private StksendField As Boolean
        
        Private StkreceiveField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private User1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private User2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private User3Field As String
        
        Private User4Field As System.Nullable(Of Date)
        
        Private User5Field As System.Nullable(Of Date)
        
        Private User6Field As System.Nullable(Of Double)
        
        Private User7Field As System.Nullable(Of Double)
        
        Private User8Field As System.Nullable(Of Short)
        
        Private User9Field As System.Nullable(Of Short)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Siteid() As String
            Get
                Return Me.SiteidField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SiteidField, value) <> true) Then
                    Me.SiteidField = value
                    Me.RaisePropertyChanged("Siteid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Cityid() As String
            Get
                Return Me.CityidField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CityidField, value) <> true) Then
                    Me.CityidField = value
                    Me.RaisePropertyChanged("Cityid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Countryid() As String
            Get
                Return Me.CountryidField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CountryidField, value) <> true) Then
                    Me.CountryidField = value
                    Me.RaisePropertyChanged("Countryid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Addr1() As String
            Get
                Return Me.Addr1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Addr1Field, value) <> true) Then
                    Me.Addr1Field = value
                    Me.RaisePropertyChanged("Addr1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property IdPais() As String
            Get
                Return Me.IdPaisField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdPaisField, value) <> true) Then
                    Me.IdPaisField = value
                    Me.RaisePropertyChanged("IdPais")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property IdDepartamento() As String
            Get
                Return Me.IdDepartamentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdDepartamentoField, value) <> true) Then
                    Me.IdDepartamentoField = value
                    Me.RaisePropertyChanged("IdDepartamento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property IdProvincia() As String
            Get
                Return Me.IdProvinciaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdProvinciaField, value) <> true) Then
                    Me.IdProvinciaField = value
                    Me.RaisePropertyChanged("IdProvincia")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property IdDistrito() As String
            Get
                Return Me.IdDistritoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdDistritoField, value) <> true) Then
                    Me.IdDistritoField = value
                    Me.RaisePropertyChanged("IdDistrito")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property IdRegion() As String
            Get
                Return Me.IdRegionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdRegionField, value) <> true) Then
                    Me.IdRegionField = value
                    Me.RaisePropertyChanged("IdRegion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property Pais() As String
            Get
                Return Me.PaisField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PaisField, value) <> true) Then
                    Me.PaisField = value
                    Me.RaisePropertyChanged("Pais")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property Departamento() As String
            Get
                Return Me.DepartamentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DepartamentoField, value) <> true) Then
                    Me.DepartamentoField = value
                    Me.RaisePropertyChanged("Departamento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Property Provincia() As String
            Get
                Return Me.ProvinciaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProvinciaField, value) <> true) Then
                    Me.ProvinciaField = value
                    Me.RaisePropertyChanged("Provincia")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public Property Distrito() As String
            Get
                Return Me.DistritoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DistritoField, value) <> true) Then
                    Me.DistritoField = value
                    Me.RaisePropertyChanged("Distrito")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property Addr2() As String
            Get
                Return Me.Addr2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Addr2Field, value) <> true) Then
                    Me.Addr2Field = value
                    Me.RaisePropertyChanged("Addr2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Property Fono1() As String
            Get
                Return Me.Fono1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Fono1Field, value) <> true) Then
                    Me.Fono1Field = value
                    Me.RaisePropertyChanged("Fono1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=16)>  _
        Public Property Fono2() As String
            Get
                Return Me.Fono2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Fono2Field, value) <> true) Then
                    Me.Fono2Field = value
                    Me.RaisePropertyChanged("Fono2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=17)>  _
        Public Property Fax() As String
            Get
                Return Me.FaxField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaxField, value) <> true) Then
                    Me.FaxField = value
                    Me.RaisePropertyChanged("Fax")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=18)>  _
        Public Property Status() As System.Nullable(Of Boolean)
            Get
                Return Me.StatusField
            End Get
            Set
                If (Me.StatusField.Equals(value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=19)>  _
        Public Property Startdateinven() As System.Nullable(Of Date)
            Get
                Return Me.StartdateinvenField
            End Get
            Set
                If (Me.StartdateinvenField.Equals(value) <> true) Then
                    Me.StartdateinvenField = value
                    Me.RaisePropertyChanged("Startdateinven")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=20)>  _
        Public Property Enddateinven() As System.Nullable(Of Date)
            Get
                Return Me.EnddateinvenField
            End Get
            Set
                If (Me.EnddateinvenField.Equals(value) <> true) Then
                    Me.EnddateinvenField = value
                    Me.RaisePropertyChanged("Enddateinven")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=21)>  _
        Public Property Adjust() As System.Nullable(Of Boolean)
            Get
                Return Me.AdjustField
            End Get
            Set
                If (Me.AdjustField.Equals(value) <> true) Then
                    Me.AdjustField = value
                    Me.RaisePropertyChanged("Adjust")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=22)>  _
        Public Property Attn() As String
            Get
                Return Me.AttnField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AttnField, value) <> true) Then
                    Me.AttnField = value
                    Me.RaisePropertyChanged("Attn")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=23)>  _
        Public Property Userid() As String
            Get
                Return Me.UseridField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UseridField, value) <> true) Then
                    Me.UseridField = value
                    Me.RaisePropertyChanged("Userid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=24)>  _
        Public Property Stknew() As Boolean
            Get
                Return Me.StknewField
            End Get
            Set
                If (Me.StknewField.Equals(value) <> true) Then
                    Me.StknewField = value
                    Me.RaisePropertyChanged("Stknew")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=25)>  _
        Public Property Stkmodify() As Boolean
            Get
                Return Me.StkmodifyField
            End Get
            Set
                If (Me.StkmodifyField.Equals(value) <> true) Then
                    Me.StkmodifyField = value
                    Me.RaisePropertyChanged("Stkmodify")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=26)>  _
        Public Property Stkdelete() As Boolean
            Get
                Return Me.StkdeleteField
            End Get
            Set
                If (Me.StkdeleteField.Equals(value) <> true) Then
                    Me.StkdeleteField = value
                    Me.RaisePropertyChanged("Stkdelete")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=27)>  _
        Public Property Stksend() As Boolean
            Get
                Return Me.StksendField
            End Get
            Set
                If (Me.StksendField.Equals(value) <> true) Then
                    Me.StksendField = value
                    Me.RaisePropertyChanged("Stksend")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=28)>  _
        Public Property Stkreceive() As Boolean
            Get
                Return Me.StkreceiveField
            End Get
            Set
                If (Me.StkreceiveField.Equals(value) <> true) Then
                    Me.StkreceiveField = value
                    Me.RaisePropertyChanged("Stkreceive")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=29)>  _
        Public Property User1() As String
            Get
                Return Me.User1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.User1Field, value) <> true) Then
                    Me.User1Field = value
                    Me.RaisePropertyChanged("User1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=30)>  _
        Public Property User2() As String
            Get
                Return Me.User2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.User2Field, value) <> true) Then
                    Me.User2Field = value
                    Me.RaisePropertyChanged("User2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=31)>  _
        Public Property User3() As String
            Get
                Return Me.User3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.User3Field, value) <> true) Then
                    Me.User3Field = value
                    Me.RaisePropertyChanged("User3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=32)>  _
        Public Property User4() As System.Nullable(Of Date)
            Get
                Return Me.User4Field
            End Get
            Set
                If (Me.User4Field.Equals(value) <> true) Then
                    Me.User4Field = value
                    Me.RaisePropertyChanged("User4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=33)>  _
        Public Property User5() As System.Nullable(Of Date)
            Get
                Return Me.User5Field
            End Get
            Set
                If (Me.User5Field.Equals(value) <> true) Then
                    Me.User5Field = value
                    Me.RaisePropertyChanged("User5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=34)>  _
        Public Property User6() As System.Nullable(Of Double)
            Get
                Return Me.User6Field
            End Get
            Set
                If (Me.User6Field.Equals(value) <> true) Then
                    Me.User6Field = value
                    Me.RaisePropertyChanged("User6")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=35)>  _
        Public Property User7() As System.Nullable(Of Double)
            Get
                Return Me.User7Field
            End Get
            Set
                If (Me.User7Field.Equals(value) <> true) Then
                    Me.User7Field = value
                    Me.RaisePropertyChanged("User7")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=36)>  _
        Public Property User8() As System.Nullable(Of Short)
            Get
                Return Me.User8Field
            End Get
            Set
                If (Me.User8Field.Equals(value) <> true) Then
                    Me.User8Field = value
                    Me.RaisePropertyChanged("User8")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=37)>  _
        Public Property User9() As System.Nullable(Of Short)
            Get
                Return Me.User9Field
            End Get
            Set
                If (Me.User9Field.Equals(value) <> true) Then
                    Me.User9Field = value
                    Me.RaisePropertyChanged("User9")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="listarPecsa.ServiciosExternosSoap")>  _
    Public Interface ServiciosExternosSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarConsumos", ReplyAction:="*")>  _
        Function ListarConsumos(ByVal request As listarPecsa.ListarConsumosRequest) As listarPecsa.ListarConsumosResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListarEstacionesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarEstaciones", ReplyAction:="*")>  _
        Function ListarEstaciones(ByVal request As listarPecsa.ListarEstacionesRequest) As listarPecsa.ListarEstacionesResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListarConsumosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListarConsumos", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As listarPecsa.ListarConsumosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As listarPecsa.ListarConsumosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ListarConsumosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public contrasena As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public siteid As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public nbrdocument As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public placa As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public fechaInicio As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public fechaFinal As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal contrasena As String, ByVal siteid As String, ByVal nbrdocument As String, ByVal placa As String, ByVal fechaInicio As String, ByVal fechaFinal As String)
            MyBase.New
            Me.usuario = usuario
            Me.contrasena = contrasena
            Me.siteid = siteid
            Me.nbrdocument = nbrdocument
            Me.placa = placa
            Me.fechaInicio = fechaInicio
            Me.fechaFinal = fechaFinal
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListarConsumosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListarConsumosResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As listarPecsa.ListarConsumosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As listarPecsa.ListarConsumosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ListarConsumosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ListarConsumosResult() As listarPecsa.TransaccionInfo
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public [error] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListarConsumosResult() As listarPecsa.TransaccionInfo, ByVal [error] As String)
            MyBase.New
            Me.ListarConsumosResult = ListarConsumosResult
            Me.[error] = [error]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListarEstacionesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListarEstaciones", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As listarPecsa.ListarEstacionesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As listarPecsa.ListarEstacionesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class ListarEstacionesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListarEstacionesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListarEstacionesResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As listarPecsa.ListarEstacionesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As listarPecsa.ListarEstacionesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ListarEstacionesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ListarEstacionesResult() As listarPecsa.SiteInfo
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public [error] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListarEstacionesResult() As listarPecsa.SiteInfo, ByVal [error] As String)
            MyBase.New
            Me.ListarEstacionesResult = ListarEstacionesResult
            Me.[error] = [error]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiciosExternosSoapChannel
        Inherits listarPecsa.ServiciosExternosSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiciosExternosSoapClient
        Inherits System.ServiceModel.ClientBase(Of listarPecsa.ServiciosExternosSoap)
        Implements listarPecsa.ServiciosExternosSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function listarPecsa_ServiciosExternosSoap_ListarConsumos(ByVal request As listarPecsa.ListarConsumosRequest) As listarPecsa.ListarConsumosResponse Implements listarPecsa.ServiciosExternosSoap.ListarConsumos
            Return MyBase.Channel.ListarConsumos(request)
        End Function
        
        Public Function ListarConsumos(ByVal usuario As String, ByVal contrasena As String, ByVal siteid As String, ByVal nbrdocument As String, ByVal placa As String, ByVal fechaInicio As String, ByVal fechaFinal As String, <System.Runtime.InteropServices.OutAttribute()> ByRef [error] As String) As listarPecsa.TransaccionInfo()
            Dim inValue As listarPecsa.ListarConsumosRequest = New listarPecsa.ListarConsumosRequest()
            inValue.Body = New listarPecsa.ListarConsumosRequestBody()
            inValue.Body.usuario = usuario
            inValue.Body.contrasena = contrasena
            inValue.Body.siteid = siteid
            inValue.Body.nbrdocument = nbrdocument
            inValue.Body.placa = placa
            inValue.Body.fechaInicio = fechaInicio
            inValue.Body.fechaFinal = fechaFinal
            Dim retVal As listarPecsa.ListarConsumosResponse = CType(Me,listarPecsa.ServiciosExternosSoap).ListarConsumos(inValue)
            [error] = retVal.Body.[error]
            Return retVal.Body.ListarConsumosResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function listarPecsa_ServiciosExternosSoap_ListarEstaciones(ByVal request As listarPecsa.ListarEstacionesRequest) As listarPecsa.ListarEstacionesResponse Implements listarPecsa.ServiciosExternosSoap.ListarEstaciones
            Return MyBase.Channel.ListarEstaciones(request)
        End Function
        
        Public Function ListarEstaciones(<System.Runtime.InteropServices.OutAttribute()> ByRef [error] As String) As listarPecsa.SiteInfo()
            Dim inValue As listarPecsa.ListarEstacionesRequest = New listarPecsa.ListarEstacionesRequest()
            inValue.Body = New listarPecsa.ListarEstacionesRequestBody()
            Dim retVal As listarPecsa.ListarEstacionesResponse = CType(Me,listarPecsa.ServiciosExternosSoap).ListarEstaciones(inValue)
            [error] = retVal.Body.[error]
            Return retVal.Body.ListarEstacionesResult
        End Function
    End Class
End Namespace
