'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34209
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WCF_CpeIndu
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WCF_CpeIndu.IWCF_Cpe")>  _
    Public Interface IWCF_Cpe
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWCF_Cpe/Mensaje_Inicio", ReplyAction:="http://tempuri.org/IWCF_Cpe/Mensaje_InicioResponse")>  _
        Function Mensaje_Inicio(ByVal Empresa As String, ByVal direccion As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWCF_Cpe/Inicializar", ReplyAction:="http://tempuri.org/IWCF_Cpe/InicializarResponse")>  _
        Function Inicializar(ByVal Empresa As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWCF_Cpe/GenerarXML_CPE", ReplyAction:="http://tempuri.org/IWCF_Cpe/GenerarXML_CPEResponse")>  _
        Function GenerarXML_CPE(ByVal dsCab As System.Data.DataSet, ByVal fecha_emision As Date, ByVal tipo_documento As String, ByVal ruta_cpe As String, ByVal empresa As String, ByVal dtResumen As System.Data.DataTable, ByVal b_baja As Boolean) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWCF_Cpe/EnviarXML_CPE", ReplyAction:="http://tempuri.org/IWCF_Cpe/EnviarXML_CPEResponse")>  _
        Function EnviarXML_CPE(ByVal nombre As String, ByVal cdrXML As String, ByVal definicion As String, ByVal valorResumen As String, ByVal firma As String, ByVal ticket As String, ByVal dsCab As System.Data.DataSet, ByVal tipo_documento As String, ByVal ruta_cpe As String, ByVal empresa As String, ByVal b_baja As Boolean, ByVal b_env_ind As Boolean) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWCF_Cpe/EnviarCPE_PortalConsultas", ReplyAction:="http://tempuri.org/IWCF_Cpe/EnviarCPE_PortalConsultasResponse")>  _
        Function EnviarCPE_PortalConsultas(ByVal ds As System.Data.DataSet) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWCF_Cpe/GetStatus_Ticket", ReplyAction:="http://tempuri.org/IWCF_Cpe/GetStatus_TicketResponse")>  _
        Function GetStatus_Ticket(ByVal ruta_cpe As String, ByVal ticket As String, ByVal nombre_xml As String, ByVal tipo_documento As String, ByVal b_baja As Boolean, ByVal empresa As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWCF_Cpe/GetStatus_Documento", ReplyAction:="http://tempuri.org/IWCF_Cpe/GetStatus_DocumentoResponse")>  _
        Function GetStatus_Documento(ByVal dtComprobante As System.Data.DataTable, ByVal ruta_cpe As String, ByVal empresa As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IWCF_CpeChannel
        Inherits WCF_CpeIndu.IWCF_Cpe, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WCF_CpeClient
        Inherits System.ServiceModel.ClientBase(Of WCF_CpeIndu.IWCF_Cpe)
        Implements WCF_CpeIndu.IWCF_Cpe
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Mensaje_Inicio(ByVal Empresa As String, ByVal direccion As String) As String Implements WCF_CpeIndu.IWCF_Cpe.Mensaje_Inicio
            Return MyBase.Channel.Mensaje_Inicio(Empresa, direccion)
        End Function
        
        Public Function Inicializar(ByVal Empresa As String) As Boolean Implements WCF_CpeIndu.IWCF_Cpe.Inicializar
            Return MyBase.Channel.Inicializar(Empresa)
        End Function
        
        Public Function GenerarXML_CPE(ByVal dsCab As System.Data.DataSet, ByVal fecha_emision As Date, ByVal tipo_documento As String, ByVal ruta_cpe As String, ByVal empresa As String, ByVal dtResumen As System.Data.DataTable, ByVal b_baja As Boolean) As String Implements WCF_CpeIndu.IWCF_Cpe.GenerarXML_CPE
            Return MyBase.Channel.GenerarXML_CPE(dsCab, fecha_emision, tipo_documento, ruta_cpe, empresa, dtResumen, b_baja)
        End Function
        
        Public Function EnviarXML_CPE(ByVal nombre As String, ByVal cdrXML As String, ByVal definicion As String, ByVal valorResumen As String, ByVal firma As String, ByVal ticket As String, ByVal dsCab As System.Data.DataSet, ByVal tipo_documento As String, ByVal ruta_cpe As String, ByVal empresa As String, ByVal b_baja As Boolean, ByVal b_env_ind As Boolean) As String Implements WCF_CpeIndu.IWCF_Cpe.EnviarXML_CPE
            Return MyBase.Channel.EnviarXML_CPE(nombre, cdrXML, definicion, valorResumen, firma, ticket, dsCab, tipo_documento, ruta_cpe, empresa, b_baja, b_env_ind)
        End Function
        
        Public Function EnviarCPE_PortalConsultas(ByVal ds As System.Data.DataSet) As String Implements WCF_CpeIndu.IWCF_Cpe.EnviarCPE_PortalConsultas
            Return MyBase.Channel.EnviarCPE_PortalConsultas(ds)
        End Function
        
        Public Function GetStatus_Ticket(ByVal ruta_cpe As String, ByVal ticket As String, ByVal nombre_xml As String, ByVal tipo_documento As String, ByVal b_baja As Boolean, ByVal empresa As String) As String Implements WCF_CpeIndu.IWCF_Cpe.GetStatus_Ticket
            Return MyBase.Channel.GetStatus_Ticket(ruta_cpe, ticket, nombre_xml, tipo_documento, b_baja, empresa)
        End Function
        
        Public Function GetStatus_Documento(ByVal dtComprobante As System.Data.DataTable, ByVal ruta_cpe As String, ByVal empresa As String) As String Implements WCF_CpeIndu.IWCF_Cpe.GetStatus_Documento
            Return MyBase.Channel.GetStatus_Documento(dtComprobante, ruta_cpe, empresa)
        End Function
    End Class
End Namespace
